/// Person deduplication demo.
///
/// Reads a synthetic Dutch BRP person registry generated by
/// `data_generator/generate_demo_persons.py`, runs the full zer pipeline in
/// deduplication mode, and evaluates the results against the ground truth pairs.
use std::{collections::HashSet, path::Path};

use demo_common::{
    init_tracing, print_cluster_tree, print_score_histogram, section, viz::ClusterEntry,
};
use zer_cluster::ZalEntityStore;
use zer_core::{
    record::{Record, RecordId},
    schema::{FieldKind, SchemaBuilder},
};
use zer_pipeline::{Pipeline, PipelineConfig};

const DATA_DIR: &str = "data/demos/persons";

// ── CSV row structs ───────────────────────────────────────────────────────────

#[derive(Debug, serde::Deserialize)]
#[allow(dead_code)]
struct PersonRow {
    record_id: u64,
    #[serde(default)]
    bsn: String,
    voornamen: String,
    #[serde(default)]
    tussenvoegsel: String,
    achternaam: String,
    geboortedatum: String,
    #[serde(default)]
    geboorteplaats: String,
    geslacht: String,
    straatnaam: String,
    huisnummer: String,
    postcode: String,
    woonplaats: String,
}

#[derive(Debug, serde::Deserialize)]
struct GroundTruthRow {
    record_id_a: u64,
    record_id_b: u64,
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn load_records(path: &Path) -> Vec<(PersonRow, Record)> {
    let mut rdr = csv::Reader::from_path(path).expect("open records.csv");
    rdr.deserialize::<PersonRow>()
        .map(|r| {
            let row = r.expect("parse record row");
            let id = row.record_id;
            let rec = Record::new(id)
                .insert("voornamen", row.voornamen.clone())
                .insert("tussenvoegsel", row.tussenvoegsel.clone())
                .insert("achternaam", row.achternaam.clone())
                .insert("geboortedatum", row.geboortedatum.clone())
                .insert("geslacht", row.geslacht.clone())
                .insert("straatnaam", row.straatnaam.clone())
                .insert("huisnummer", row.huisnummer.clone())
                .insert("postcode", row.postcode.clone())
                .insert("woonplaats", row.woonplaats.clone());
            (row, rec)
        })
        .collect()
}

fn load_ground_truth(path: &Path) -> HashSet<(u64, u64)> {
    let mut rdr = csv::Reader::from_path(path).expect("open ground_truth.csv");
    rdr.deserialize::<GroundTruthRow>()
        .map(|r| {
            let row = r.expect("parse ground truth row");
            (
                row.record_id_a.min(row.record_id_b),
                row.record_id_a.max(row.record_id_b),
            )
        })
        .collect()
}

fn normalise_pair(a: RecordId, b: RecordId) -> (u64, u64) {
    (a.min(b), a.max(b))
}

#[tokio::main]
async fn main() {
    init_tracing();

    let data_dir = Path::new(DATA_DIR);
    let rec_path = data_dir.join("records.csv");
    let gt_path = data_dir.join("ground_truth.csv");

    // ── Load data ─────────────────────────────────────────────────────────────
    section("Loading dataset");

    if !rec_path.exists() {
        eprintln!(
            "Dataset not found at {}\n  Run: python data_generator/generate_demo_persons.py",
            rec_path.display()
        );
        std::process::exit(1);
    }

    let rows_and_records = load_records(&rec_path);
    let ground_truth = load_ground_truth(&gt_path);

    println!("{} records loaded", rows_and_records.len());
    println!("{} ground-truth duplicate pairs", ground_truth.len());

    let records: Vec<Record> = rows_and_records.iter().map(|(_, r)| r.clone()).collect();

    // ── Build pipeline ────────────────────────────────────────────────────────
    section("Building pipeline");

    let schema = SchemaBuilder::new()
        .field("voornamen", FieldKind::Name)
        .field("achternaam", FieldKind::Name)
        .field("geboortedatum", FieldKind::Date)
        .field("geslacht", FieldKind::FreeText)
        .field("straatnaam", FieldKind::FreeText)
        .field("postcode", FieldKind::FreeText)
        .field("woonplaats", FieldKind::FreeText)
        .build()
        .expect("build schema");

    let store = ZalEntityStore::open_in_memory().expect("open entity store");

    let tmpdir = std::env::temp_dir();
    let zsm = tmpdir.join("demo_persons.zsm");

    let pipeline = Pipeline::builder()
        .schema(schema)
        .store(store)
        .config(PipelineConfig {
            registry_path: zsm,
            ..PipelineConfig::default()
        })
        .build()
        .expect("build pipeline");

    // ── Run batch ─────────────────────────────────────────────────────────────
    section("Running deduplication");

    let report = pipeline.run_batch(records).await.expect("run_batch");

    println!("startup mode    : {}", report.startup_mode);
    println!("total records   : {}", report.total_records);
    println!("candidate pairs : {}", report.candidate_pairs);
    println!("auto-matched    : {}", report.auto_matched);
    println!("borderline      : {}", report.borderline);
    println!("auto-rejected   : {}", report.auto_rejected);
    println!("entities created: {}", report.entities_created);
    println!("entities updated: {}", report.entities_updated);
    println!("elapsed         : {} ms", report.elapsed_ms);

    // ── Score distribution ────────────────────────────────────────────────────
    section("Score distribution");

    if !report.scored_pairs.is_empty() {
        let scores: Vec<f32> = report.scored_pairs.iter().map(|&(_, _, s)| s).collect();
        let auto_match = 0.85_f32;
        let auto_reject = 0.15_f32;
        print_score_histogram(&scores, auto_match, auto_reject);
    } else {
        println!("  (set SCORED_PAIR_COLLECT=1 to see score distribution)");
    }

    // ── Evaluate against ground truth ─────────────────────────────────────────
    section("Evaluation");

    let view = pipeline.cluster_view();
    let clusters: Vec<_> = view.into_iter().collect();
    let multi_member: Vec<_> = clusters
        .iter()
        .filter(|(e, _)| e.members.len() > 1)
        .collect();

    let mut predicted: HashSet<(u64, u64)> = HashSet::new();
    for (entity, _) in &multi_member {
        let ids: Vec<RecordId> = entity.members.iter().map(|m| m.record_id).collect();
        for i in 0..ids.len() {
            for j in (i + 1)..ids.len() {
                predicted.insert(normalise_pair(ids[i], ids[j]));
            }
        }
    }

    let tp = predicted.intersection(&ground_truth).count();
    let fp = predicted.difference(&ground_truth).count();
    let fn_ = ground_truth.difference(&predicted).count();

    let precision = if tp + fp > 0 {
        tp as f64 / (tp + fp) as f64
    } else {
        0.0
    };
    let recall = if tp + fn_ > 0 {
        tp as f64 / (tp + fn_) as f64
    } else {
        0.0
    };
    let f1 = if precision + recall > 0.0 {
        2.0 * precision * recall / (precision + recall)
    } else {
        0.0
    };

    println!("true positives  : {}", tp);
    println!("false positives : {}", fp);
    println!("false negatives : {}", fn_);
    println!("precision       : {:.3}", precision);
    println!("recall          : {:.3}", recall);
    println!("F1              : {:.3}", f1);

    // ── Cluster tree (sample) ─────────────────────────────────────────────────
    section("Entity clusters (sample)");

    let entries: Vec<ClusterEntry> = multi_member
        .iter()
        .take(20)
        .map(|(entity, recs)| {
            let record_ids: Vec<u64> = entity.members.iter().map(|m| m.record_id).collect();
            let best_scores: Vec<f32> = entity.members.iter().map(|m| m.score).collect();
            let labels: Vec<String> = recs
                .iter()
                .map(|r| {
                    let naam = format!(
                        "{} {}",
                        r.text("voornamen").unwrap_or(""),
                        r.text("achternaam").unwrap_or("")
                    );
                    naam.trim().to_owned()
                })
                .collect();
            ClusterEntry {
                entity_id: entity.id,
                record_ids,
                best_scores,
                labels,
            }
        })
        .collect();

    print_cluster_tree(&entries, 10);

    section("Done");
}
