/// Cross-source linkage demo.
///
/// Links two independently-perturbed views of the same population:
///   Source A, authoritative municipal register (with BSN, minimal perturbation)
///   Source B, downstream benefits system (name variants, address lag, no BSN)
///
/// Generated by `data_generator/generate_demo_linkage.py`.
use std::{
    collections::HashSet,
    path::Path,
};

use demo_common::{
    init_tracing, section,
    print_pair_table,
    viz::PairRow,
};
use zer_cluster::ZalEntityStore;
use zer_core::{
    record::Record,
    schema::{FieldKind, SchemaBuilder},
};
use zer_pipeline::{LinkMode, Pipeline, PipelineConfig};

const DATA_DIR: &str = "data/demos/linkage";

#[derive(Debug, serde::Deserialize)]
#[allow(dead_code)]
struct SourceARow {
    record_id:     u64,
    #[serde(default)] bsn: String,
    voornamen:     String,
    #[serde(default)] tussenvoegsel: String,
    achternaam:    String,
    geboortedatum: String,
    geslacht:      String,
    straatnaam:    String,
    huisnummer:    String,
    postcode:      String,
    woonplaats:    String,
}

#[derive(Debug, serde::Deserialize)]
struct SourceBRow {
    record_id:     u64,
    voornamen:     String,
    #[serde(default)] tussenvoegsel: String,
    achternaam:    String,
    geboortedatum: String,
    geslacht:      String,
    straatnaam:    String,
    huisnummer:    String,
    postcode:      String,
    woonplaats:    String,
}

#[derive(Debug, serde::Deserialize)]
struct GroundTruthRow {
    record_id_a: u64,
    record_id_b: u64,
}

fn load_source_a(path: &Path) -> Vec<(SourceARow, Record)> {
    let mut rdr = csv::Reader::from_path(path).expect("open source_a.csv");
    rdr.deserialize::<SourceARow>()
        .map(|r| {
            let row = r.expect("parse source_a row");
            let id  = row.record_id;
            let rec = Record::new(id)
                .with_source("A")
                .insert("voornamen",     row.voornamen.clone())
                .insert("tussenvoegsel", row.tussenvoegsel.clone())
                .insert("achternaam",    row.achternaam.clone())
                .insert("geboortedatum", row.geboortedatum.clone())
                .insert("geslacht",      row.geslacht.clone())
                .insert("straatnaam",    row.straatnaam.clone())
                .insert("huisnummer",    row.huisnummer.clone())
                .insert("postcode",      row.postcode.clone())
                .insert("woonplaats",    row.woonplaats.clone());
            (row, rec)
        })
        .collect()
}

fn load_source_b(path: &Path, id_offset: u64) -> Vec<(SourceBRow, Record)> {
    let mut rdr = csv::Reader::from_path(path).expect("open source_b.csv");
    rdr.deserialize::<SourceBRow>()
        .map(|r| {
            let row = r.expect("parse source_b row");
            // Offset IDs to avoid collisions with source A in the same record store.
            let id  = row.record_id + id_offset;
            let rec = Record::new(id)
                .with_source("B")
                .insert("voornamen",     row.voornamen.clone())
                .insert("tussenvoegsel", row.tussenvoegsel.clone())
                .insert("achternaam",    row.achternaam.clone())
                .insert("geboortedatum", row.geboortedatum.clone())
                .insert("geslacht",      row.geslacht.clone())
                .insert("straatnaam",    row.straatnaam.clone())
                .insert("huisnummer",    row.huisnummer.clone())
                .insert("postcode",      row.postcode.clone())
                .insert("woonplaats",    row.woonplaats.clone());
            (row, rec)
        })
        .collect()
}

fn load_ground_truth(path: &Path) -> HashSet<(u64, u64)> {
    let mut rdr = csv::Reader::from_path(path).expect("open ground_truth.csv");
    rdr.deserialize::<GroundTruthRow>()
        .map(|r| {
            let row = r.expect("parse ground truth row");
            (row.record_id_a, row.record_id_b)
        })
        .collect()
}

#[tokio::main]
async fn main() {
    init_tracing();

    let data_dir = Path::new(DATA_DIR);
    let path_a   = data_dir.join("source_a.csv");
    let path_b   = data_dir.join("source_b.csv");
    let path_gt  = data_dir.join("ground_truth.csv");

    // ── Load ──────────────────────────────────────────────────────────────────
    section("Loading datasets");

    if !path_a.exists() {
        eprintln!(
            "Dataset not found at {}\n  Run: python data_generator/generate_demo_linkage.py",
            path_a.display()
        );
        std::process::exit(1);
    }

    let a_rows = load_source_a(&path_a);
    // Source B record IDs are offset so they do not collide with A.
    let id_offset = a_rows.len() as u64 + 1;
    let b_rows    = load_source_b(&path_b, id_offset);
    let ground_truth = load_ground_truth(&path_gt);

    println!("source A: {} records", a_rows.len());
    println!("source B: {} records", b_rows.len());
    println!("ground truth: {} linked pairs", ground_truth.len());

    // ── Build pipeline ────────────────────────────────────────────────────────
    section("Building pipeline");

    let schema = SchemaBuilder::new()
        .field("voornamen",     FieldKind::Name)
        .field("achternaam",    FieldKind::Name)
        .field("geboortedatum", FieldKind::Date)
        .field("geslacht",      FieldKind::FreeText)
        .field("straatnaam",    FieldKind::FreeText)
        .field("postcode",      FieldKind::FreeText)
        .build()
        .expect("build schema");

    let store  = ZalEntityStore::open_in_memory().expect("open entity store");
    let tmpdir = std::env::temp_dir();
    let zsm    = tmpdir.join("demo_linkage.zsm");

    let pipeline = Pipeline::builder()
        .schema(schema)
        .store(store)
        .config(PipelineConfig {
            registry_path: zsm,
            link_mode: LinkMode::LinkOnly,
            ..PipelineConfig::default()
        })
        .build()
        .expect("build pipeline");

    // ── Run ───────────────────────────────────────────────────────────────────
    section("Running cross-source linkage");

    let mut all_records: Vec<Record> = Vec::new();
    all_records.extend(a_rows.iter().map(|(_, r)| r.clone()));
    all_records.extend(b_rows.iter().map(|(_, r)| r.clone()));

    let report = pipeline.run_batch(all_records).await.expect("run_batch");

    println!("startup mode      : {}", report.startup_mode);
    println!("total records     : {}", report.total_records);
    println!("candidate pairs   : {}", report.candidate_pairs);
    println!("cross-source pairs: {}", report.cross_source_pairs);
    println!("auto-matched      : {}", report.auto_matched);
    println!("borderline        : {}", report.borderline);
    println!("auto-rejected     : {}", report.auto_rejected);
    println!("entities created  : {}", report.entities_created);
    println!("elapsed           : {} ms", report.elapsed_ms);

    // ── Evaluate ──────────────────────────────────────────────────────────────
    section("Evaluation");

    // Build a lookup: original source B id → offset id
    let _b_id_map: std::collections::HashMap<u64, u64> = b_rows.iter()
        .map(|(row, rec)| (row.record_id, rec.id))
        .collect();

    let view = pipeline.cluster_view();
    let linked = view.linked_pairs();

    // Normalise predicted pairs to (original_a_id, original_b_id)
    let predicted: HashSet<(u64, u64)> = linked.iter()
        .map(|lp| {
            // Determine which of the two IDs is from source A and which from B.
            // Source A IDs fit in [1..=|A|]; source B IDs are offset.
            let (raw_a, raw_b) = if lp.source_a.as_deref() == Some("A") {
                (lp.record_id_a, lp.record_id_b - id_offset)
            } else {
                (lp.record_id_b, lp.record_id_a - id_offset)
            };
            (raw_a, raw_b)
        })
        .collect();

    let tp  = predicted.intersection(&ground_truth).count();
    let fp  = predicted.difference(&ground_truth).count();
    let fn_ = ground_truth.difference(&predicted).count();

    let precision = if tp + fp > 0 { tp as f64 / (tp + fp) as f64 } else { 0.0 };
    let recall    = if tp + fn_ > 0 { tp as f64 / (tp + fn_) as f64 } else { 0.0 };
    let f1        = if precision + recall > 0.0 { 2.0 * precision * recall / (precision + recall) } else { 0.0 };

    println!("true positives  : {}", tp);
    println!("false positives : {}", fp);
    println!("false negatives : {}", fn_);
    println!("precision       : {:.3}", precision);
    println!("recall          : {:.3}", recall);
    println!("F1              : {:.3}", f1);

    // ── Pair table (sample) ───────────────────────────────────────────────────
    section("Linked pairs (sample)");

    // Build quick name lookups for display.
    let a_names: std::collections::HashMap<u64, String> = a_rows.iter()
        .map(|(row, _)| {
            let name = format!("{} {}", row.voornamen, row.achternaam);
            (row.record_id, name)
        })
        .collect();

    let b_names: std::collections::HashMap<u64, String> = b_rows.iter()
        .map(|(row, rec)| {
            let name = format!("{} {}", row.voornamen, row.achternaam);
            (rec.id, name)
        })
        .collect();

    let pair_rows: Vec<PairRow> = linked.iter().take(30).map(|lp| {
        let (aid, bid) = if lp.source_a.as_deref() == Some("A") {
            (lp.record_id_a, lp.record_id_b)
        } else {
            (lp.record_id_b, lp.record_id_a)
        };
        PairRow {
            score: lp.score,
            a_fields: vec![
                ("id".into(),   aid.to_string()),
                ("name".into(), a_names.get(&aid).cloned().unwrap_or_default()),
            ],
            b_fields: vec![
                ("id".into(),   (bid - id_offset).to_string()),
                ("name".into(), b_names.get(&bid).cloned().unwrap_or_default()),
            ],
        }
    }).collect();

    print_pair_table(&pair_rows, 15);

    section("Done");
}
